import type { Agent } from '../types/agent.js';
import type { TestLog, ScenarioResult, StepResult } from '../types/test-log.js';
import type { TestReport } from '../types/test-report.js';

type Severity = 'critical' | 'high' | 'low';

export class Reporter implements Agent<TestLog, TestReport> {
  readonly name = 'Reporter';

  async run(input: TestLog): Promise<TestReport> {
    const timestamp = new Date().toISOString();

    this.log(`Generating report for ${input.url} (${input.summary.total} scenarios)`);

    const html = this.generateHtml(input, timestamp);

    this.log(`Report generated (${html.length} chars)`);

    return {
      html,
      url: input.url,
      timestamp,
      summary: input.summary,
      gaps: input.gaps,
    };
  }

  private generateHtml(input: TestLog, timestamp: string): string {
    const displayTime = new Date(timestamp).toLocaleString();
    const passRate =
      input.summary.total > 0 ? Math.round((input.summary.passed / input.summary.total) * 100) : 0;
    const overallStatus = input.summary.failed === 0 ? 'passed' : 'failed';

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Lineup Test Report — ${this.escapeHtml(input.url)}</title>
  <style>${this.getStyles()}</style>
</head>
<body>
  <header>
    <h1>Lineup Test Report</h1>
    <p class="meta">Target: <strong>${this.escapeHtml(input.url)}</strong></p>
    <p class="meta">Generated: <strong>${this.escapeHtml(displayTime)}</strong></p>
  </header>

  ${this.renderSummarySection(input.summary, passRate, overallStatus)}

  ${input.gaps?.length ? this.renderGapsSection(input.gaps) : ''}

  <section class="scenarios">
    <h2>Scenarios</h2>
    ${input.scenarios.map((s, i) => this.renderScenarioCard(s, i)).join('\n    ')}
  </section>

  <footer>
    <p>Generated by <strong>Lineup</strong> — zero-selector UI testing</p>
  </footer>
</body>
</html>`;
  }

  private renderSummarySection(
    summary: TestLog['summary'],
    passRate: number,
    overallStatus: string,
  ): string {
    return `<section class="summary">
    <div class="summary-cards">
      <div class="card">
        <span class="card-value">${summary.total}</span>
        <span class="card-label">Total</span>
      </div>
      <div class="card card-pass">
        <span class="card-value">${summary.passed}</span>
        <span class="card-label">Passed</span>
      </div>
      <div class="card card-fail">
        <span class="card-value">${summary.failed}</span>
        <span class="card-label">Failed</span>
      </div>
      <div class="card">
        <span class="card-value">${passRate}%</span>
        <span class="card-label">Pass Rate</span>
      </div>
      <div class="card">
        <span class="card-value">${this.formatDuration(summary.durationMs)}</span>
        <span class="card-label">Duration</span>
      </div>
    </div>
    <div class="overall-status status-${overallStatus}">
      ${overallStatus === 'passed' ? '&#10003;' : '&#10007;'} ${overallStatus.toUpperCase()}
    </div>
  </section>`;
  }

  private renderGapsSection(gaps: string[]): string {
    const items = gaps
      .map(
        (gap) =>
          `<li class="gap-item"><span class="badge severity-high">GAP</span><span>${this.escapeHtml(gap)}</span></li>`,
      )
      .join('\n      ');

    return `<section class="spec-gaps">
    <h2>Specification Gaps</h2>
    <p class="spec-gaps-subtitle">${gaps.length} requirement${gaps.length === 1 ? '' : 's'} from the Jira spec not found on the page</p>
    <ul class="gap-list">
      ${items}
    </ul>
  </section>`;
  }

  private renderScenarioCard(scenario: ScenarioResult, _index: number): string {
    const statusIcon = scenario.status === 'pass' ? '&#10003;' : '&#10007;';
    const statusClass = scenario.status === 'pass' ? 'pass' : 'fail';
    const severityHtml =
      scenario.status === 'fail'
        ? `<span class="badge severity-${this.classifySeverity(scenario)}">${this.classifySeverity(scenario)}</span>`
        : '';
    const totalMs = scenario.steps.reduce((sum, s) => sum + s.durationMs, 0);

    const screenshotHtml = scenario.screenshot
      ? `<div class="screenshot-container"><img src="${this.encodeScreenshot(scenario.screenshot)}" alt="Screenshot for ${this.escapeHtml(scenario.name)}" class="screenshot"></div>`
      : '';

    return `<details class="scenario-card" ${scenario.status === 'fail' ? 'open' : ''}>
      <summary class="scenario-header">
        <span class="status-icon status-${statusClass}">${statusIcon}</span>
        <span class="scenario-name">${this.escapeHtml(scenario.name)}</span>
        ${severityHtml}
        <span class="scenario-duration">${this.formatDuration(totalMs)}</span>
      </summary>
      <div class="scenario-body">
        <table class="steps-table">
          <thead>
            <tr>
              <th>#</th>
              <th>Type</th>
              <th>Instruction</th>
              <th>Status</th>
              <th>Duration</th>
            </tr>
          </thead>
          <tbody>
            ${scenario.steps.map((s, i) => this.renderStepRow(s, i)).join('\n            ')}
          </tbody>
        </table>
        ${screenshotHtml}
      </div>
    </details>`;
  }

  private renderStepRow(step: StepResult, index: number): string {
    const statusIcon = step.status === 'pass' ? '&#10003;' : '&#10007;';
    const statusClass = step.status === 'pass' ? 'pass' : 'fail';
    const errorHtml = step.error
      ? `<div class="step-error">${this.escapeHtml(step.error)}</div>`
      : '';

    return `<tr class="step-row step-${statusClass}">
              <td>${index + 1}</td>
              <td><span class="type-badge type-${step.step.type}">${step.step.type}</span></td>
              <td>${this.escapeHtml(step.step.instruction)}${errorHtml}</td>
              <td class="status-${statusClass}">${statusIcon}</td>
              <td>${this.formatDuration(step.durationMs)}</td>
            </tr>`;
  }

  private classifySeverity(scenario: ScenarioResult): Severity {
    const failedSteps = scenario.steps.filter((s) => s.status === 'fail');
    if (failedSteps.length === 0) return 'low';

    if (scenario.steps[0] && scenario.steps[0].status === 'fail') return 'critical';

    const failRatio = failedSteps.length / scenario.steps.length;
    if (failRatio > 0.5) return 'critical';

    const hasAssertionFailure = failedSteps.some((s) => s.step.type === 'assertion');
    if (hasAssertionFailure) return 'high';

    return 'low';
  }

  private formatDuration(ms: number): string {
    if (ms < 1000) return `${ms}ms`;
    const seconds = ms / 1000;
    if (seconds < 60) return `${seconds.toFixed(1)}s`;
    const minutes = Math.floor(seconds / 60);
    const remainingSeconds = Math.round(seconds % 60);
    return `${minutes}m ${remainingSeconds}s`;
  }

  private encodeScreenshot(buffer: Buffer): string {
    return `data:image/png;base64,${buffer.toString('base64')}`;
  }

  private log(message: string): void {
    console.log(`[${this.name}] ${message}`);
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }

  private getStyles(): string {
    return `
    :root {
      --color-pass: #22c55e;
      --color-pass-bg: #f0fdf4;
      --color-fail: #ef4444;
      --color-fail-bg: #fef2f2;
      --color-critical: #dc2626;
      --color-high: #f97316;
      --color-low: #eab308;
      --color-action: #3b82f6;
      --color-assertion: #8b5cf6;
      --color-bg: #f8fafc;
      --color-surface: #ffffff;
      --color-border: #e2e8f0;
      --color-text: #1e293b;
      --color-text-secondary: #64748b;
    }

    * { margin: 0; padding: 0; box-sizing: border-box; }

    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      background: var(--color-bg);
      color: var(--color-text);
      line-height: 1.6;
      padding: 2rem;
      max-width: 1100px;
      margin: 0 auto;
    }

    header {
      margin-bottom: 2rem;
    }

    header h1 {
      font-size: 1.75rem;
      margin-bottom: 0.5rem;
    }

    .meta {
      color: var(--color-text-secondary);
      font-size: 0.9rem;
    }

    .summary {
      margin-bottom: 2rem;
    }

    .summary-cards {
      display: flex;
      gap: 1rem;
      flex-wrap: wrap;
      margin-bottom: 1rem;
    }

    .card {
      background: var(--color-surface);
      border: 1px solid var(--color-border);
      border-radius: 8px;
      padding: 1rem 1.5rem;
      display: flex;
      flex-direction: column;
      align-items: center;
      min-width: 100px;
      flex: 1;
    }

    .card-value {
      font-size: 1.75rem;
      font-weight: 700;
    }

    .card-label {
      font-size: 0.8rem;
      color: var(--color-text-secondary);
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }

    .card-pass .card-value { color: var(--color-pass); }
    .card-fail .card-value { color: var(--color-fail); }

    .overall-status {
      text-align: center;
      padding: 0.75rem;
      border-radius: 8px;
      font-weight: 700;
      font-size: 1.1rem;
    }

    .status-passed { background: var(--color-pass-bg); color: var(--color-pass); }
    .status-failed { background: var(--color-fail-bg); color: var(--color-fail); }

    .spec-gaps {
      margin-bottom: 2rem;
      background: var(--color-surface);
      border: 1px solid var(--color-border);
      border-left: 4px solid var(--color-high);
      border-radius: 8px;
      padding: 1.25rem;
    }

    .spec-gaps h2 {
      font-size: 1.3rem;
      margin-bottom: 0.25rem;
    }

    .spec-gaps-subtitle {
      color: var(--color-text-secondary);
      font-size: 0.85rem;
      margin-bottom: 1rem;
    }

    .gap-list {
      list-style: none;
      display: flex;
      flex-direction: column;
      gap: 0.25rem;
    }

    .gap-item {
      display: flex;
      align-items: center;
      gap: 0.75rem;
      padding: 0.5rem 0;
      border-bottom: 1px solid var(--color-border);
      font-size: 0.9rem;
    }

    .gap-item:last-child {
      border-bottom: none;
    }

    .scenarios h2 {
      font-size: 1.3rem;
      margin-bottom: 1rem;
    }

    .scenario-card {
      background: var(--color-surface);
      border: 1px solid var(--color-border);
      border-radius: 8px;
      margin-bottom: 0.75rem;
      overflow: hidden;
    }

    .scenario-header {
      display: flex;
      align-items: center;
      gap: 0.75rem;
      padding: 1rem 1.25rem;
      cursor: pointer;
      user-select: none;
    }

    .scenario-header:hover {
      background: var(--color-bg);
    }

    .scenario-name {
      flex: 1;
      font-weight: 600;
    }

    .scenario-duration {
      color: var(--color-text-secondary);
      font-size: 0.85rem;
    }

    .status-icon { font-weight: 700; }
    .status-pass { color: var(--color-pass); }
    .status-fail { color: var(--color-fail); }

    .badge {
      font-size: 0.7rem;
      font-weight: 700;
      padding: 0.15rem 0.5rem;
      border-radius: 4px;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: #fff;
    }

    .severity-critical { background: var(--color-critical); }
    .severity-high { background: var(--color-high); }
    .severity-low { background: var(--color-low); color: #1e293b; }

    .scenario-body {
      padding: 0 1.25rem 1.25rem;
    }

    .steps-table {
      width: 100%;
      border-collapse: collapse;
      font-size: 0.9rem;
    }

    .steps-table th {
      text-align: left;
      padding: 0.5rem 0.75rem;
      border-bottom: 2px solid var(--color-border);
      color: var(--color-text-secondary);
      font-size: 0.8rem;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }

    .steps-table td {
      padding: 0.5rem 0.75rem;
      border-bottom: 1px solid var(--color-border);
      vertical-align: top;
    }

    .step-fail td {
      background: var(--color-fail-bg);
    }

    .type-badge {
      font-size: 0.75rem;
      font-weight: 600;
      padding: 0.1rem 0.4rem;
      border-radius: 3px;
      white-space: nowrap;
    }

    .type-action { background: #dbeafe; color: var(--color-action); }
    .type-assertion { background: #ede9fe; color: var(--color-assertion); }

    .step-error {
      margin-top: 0.4rem;
      padding: 0.4rem 0.6rem;
      background: var(--color-fail-bg);
      border-left: 3px solid var(--color-fail);
      border-radius: 0 4px 4px 0;
      font-family: "SF Mono", Monaco, Consolas, monospace;
      font-size: 0.8rem;
      color: var(--color-fail);
      word-break: break-word;
    }

    .screenshot-container {
      margin-top: 1rem;
    }

    .screenshot {
      max-width: 100%;
      border: 1px solid var(--color-border);
      border-radius: 4px;
    }

    footer {
      margin-top: 3rem;
      text-align: center;
      color: var(--color-text-secondary);
      font-size: 0.85rem;
      padding-top: 1.5rem;
      border-top: 1px solid var(--color-border);
    }
    `;
  }
}
